# Generated by Django 3.2.13 on 2022-05-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220501_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ipAdress',
            new_name='ipAddress',
        ),
    ]
